In [2]:
# https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html

import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6 * 7, 3), np.float32)
objp[:, :2] = np.mgrid[0: 7, 0: 6].T.reshape(-1, 2)

# Arrays to store object points and image points from all the images.
objpoints = []  # 3d point in real world space
imgpoints = []  # 2d points in image plane.

images = glob.glob('data/images/*.jpg')
print(images)

for image in images:
    img = cv2.imread(image)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, (7, 6), None)

    if ret:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        img = cv2.drawChessboardCorners(img, (7, 6), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(500)

        ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
        print(mtx)
        print(dist)

cv2.destroyAllWindows()

['data/images/left04.jpg', 'data/images/left06.jpg', 'data/images/left09.jpg', 'data/images/1_joey-friends.jpg', 'data/images/left07.jpg', 'data/images/left05.jpg', 'data/images/left01.jpg', 'data/images/left03.jpg', 'data/images/left14.jpg', 'data/images/joye.jpg', 'data/images/left11.jpg', 'data/images/left12.jpg', 'data/images/left.jpg', 'data/images/left08.jpg', 'data/images/left13.jpg', 'data/images/left02.jpg']
[[515.51273861   0.         341.23697124]
 [  0.         515.48750138 234.27066711]
 [  0.           0.           1.        ]]
[[-2.04120057e-01 -1.03446509e+00  2.31949959e-03 -2.67680902e-03
   5.40565638e+00]]
[[568.84318872   0.         305.45921311]
 [  0.         576.68385278 235.16080587]
 [  0.           0.           1.        ]]
[[-0.3417715   0.21139459  0.00077113  0.01687714 -0.20818868]]
[[564.3049453    0.         313.66492301]
 [  0.         570.56795432 234.49413053]
 [  0.           0.           1.        ]]
[[-0.34029736  0.21984852  0.00085473  0.0145984